#!/bin/sh
# Optional authenticated SOCKS5 service, pinned to the verified WARP interface.
set -eu

ROOT="${UNLOCK_ROOT:-/opt/unlock}"
CONF_DIR="${CONF_DIR:-/etc/unlock}"
RUNTIME_DIR="${RUNTIME_DIR:-/run/unlock}"
ENABLE_SOCKS5="${ENABLE_SOCKS5:-0}"
SOCKS5_PORT="${SOCKS5_PORT:-1080}"
SOCKS5_USERNAME="${SOCKS5_USERNAME:-}"
SOCKS5_PASSWORD="${SOCKS5_PASSWORD:-}"
SOCKS5_ALLOWED_IPS="${SOCKS5_ALLOWED_IPS:-}"
SOCKS5_EXTERNAL_INTERFACE="${SOCKS5_EXTERNAL_INTERFACE:-CloudflareWARP}"
SOCKS5_EXTERNAL_IP="${SOCKS5_EXTERNAL_IP:-}"
DANTED_BIN="${DANTED_BIN:-danted}"
SOCKS_CONF="${SOCKS_CONF:-$CONF_DIR/danted.conf}"

log() { echo " >> [socks] $*"; }
fail() { echo " >> [socks] ERROR: $*" >&2; exit 1; }

is_enabled() {
  case "$ENABLE_SOCKS5" in 1|true|yes) return 0 ;; 0|false|no|'') return 1 ;; *) fail "ENABLE_SOCKS5 must be 0 or 1" ;; esac
}

valid_port() {
  case "$1" in ''|*[!0-9]*) return 1 ;; esac
  [ "$1" -ge 1 ] 2>/dev/null && [ "$1" -le 65535 ] 2>/dev/null
}

validate() {
  valid_port "$SOCKS5_PORT" || fail "invalid SOCKS5_PORT: $SOCKS5_PORT"
  case "$SOCKS5_PORT" in 53|80|443|"${DOT_PORT:-853}") fail "SOCKS5_PORT conflicts with DNS/DoT/SNI service" ;; esac
  [ -n "$SOCKS5_ALLOWED_IPS" ] || fail "SOCKS5_ALLOWED_IPS is required when SOCKS is enabled (it does not inherit ALLOWED_IPS)"
  printf '%s' "$SOCKS5_USERNAME" | grep -Eq '^[A-Za-z_][A-Za-z0-9_-]{0,31}$' || fail "SOCKS5_USERNAME must be 1-32 safe Linux username characters"
  case "$SOCKS5_USERNAME" in
    root|daemon|bin|sys|sync|games|man|lp|mail|news|uucp|proxy|www-data|backup|list|irc|_apt|nobody|systemd-*)
      fail "SOCKS5_USERNAME collides with a protected system account"
      ;;
  esac
  [ -n "$SOCKS5_PASSWORD" ] || fail "SOCKS5_PASSWORD is required when SOCKS is enabled"
  case "$SOCKS5_PASSWORD" in *:*) fail "SOCKS5_PASSWORD must not contain ':'" ;; esac
  [ "$(printf '%s\n' "$SOCKS5_PASSWORD" | wc -l)" -eq 1 ] || fail "SOCKS5_PASSWORD must not contain newline"
  [ -n "$SOCKS5_EXTERNAL_INTERFACE" ] || fail "SOCKS5_EXTERNAL_INTERFACE is required"
  if [ -z "$SOCKS5_EXTERNAL_IP" ]; then
    ip link show "$SOCKS5_EXTERNAL_INTERFACE" >/dev/null 2>&1 || fail "$SOCKS5_EXTERNAL_INTERFACE interface is unavailable"
    SOCKS5_EXTERNAL_IP="$(ip -4 -o addr show dev "$SOCKS5_EXTERNAL_INTERFACE" | awk 'NR==1{sub(/\/.*/, "", $4); print $4}')"
  fi
  printf '%s' "$SOCKS5_EXTERNAL_IP" | grep -Eq '^[0-9]+(\.[0-9]+){3}$' || fail "SOCKS5_EXTERNAL_IP must be an IPv4 address"
}

write_config() {
  mkdir -p "$CONF_DIR" "$RUNTIME_DIR"
  cat > "$SOCKS_CONF" <<EOF
# Generated by start-socks.sh. Do not edit inside the container.
logoutput: stderr
internal: 0.0.0.0 port = $SOCKS5_PORT
# Pin all proxied egress to WARP. The concrete WARP IPv4 is used as Dante's
# outbound source address; TCP CONNECT is the supported mode.
external: $SOCKS5_EXTERNAL_IP
socksmethod: username
clientmethod: none
user.privileged: root
user.unprivileged: nobody

client pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
}

socks pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    command: connect
    protocol: tcp
    socksmethod: username
}
EOF
  chmod 600 "$SOCKS_CONF"
}

case "${1:-start}" in
  config)
    is_enabled || exit 0
    validate; write_config
    ;;
  start)
    is_enabled || { log "disabled"; exit 0; }
    validate; write_config
    command -v "$DANTED_BIN" >/dev/null 2>&1 || fail "danted binary missing"
    user="${SOCKS5_USERNAME}"
    if id "$user" >/dev/null 2>&1; then
      [ -f "$CONF_DIR/socks-created-user" ] && [ "$(cat "$CONF_DIR/socks-created-user")" = "$user" ] \
        || fail "refusing to change password of pre-existing user $user"
    else
      useradd --system --no-create-home --shell /usr/sbin/nologin "$user"
      printf '%s\n' "$user" > "$CONF_DIR/socks-created-user"
      chmod 600 "$CONF_DIR/socks-created-user"
    fi
    printf '%s:%s\n' "$user" "$SOCKS5_PASSWORD" | chpasswd
    # Dante reads the hash from /etc/shadow. The process command line/config
    # never contain this password.
    log "starting SOCKS5 TCP on $SOCKS5_PORT; external=$SOCKS5_EXTERNAL_IP ($SOCKS5_EXTERNAL_INTERFACE)"
    # Dante stays foreground unless -D is given. Do not use -N here: it takes
    # a worker count, not a foreground flag. This PID is what we monitor.
    "$DANTED_BIN" -f "$SOCKS_CONF" >"$RUNTIME_DIR/danted.log" 2>&1 &
    echo $! > "$RUNTIME_DIR/danted.pid"
    sleep 1
    kill -0 "$(cat "$RUNTIME_DIR/danted.pid")" 2>/dev/null || { tail -n 100 "$RUNTIME_DIR/danted.log" >&2 || true; fail "danted exited during startup"; }
    ss -lnt | grep -Eq ":${SOCKS5_PORT}[[:space:]]" || { tail -n 100 "$RUNTIME_DIR/danted.log" >&2 || true; fail "danted is not listening on TCP $SOCKS5_PORT"; }
    log "SOCKS5 ready (separate ACL=$SOCKS5_ALLOWED_IPS)"
    ;;
  *) fail "usage: $0 [config|start]" ;;
esac
