[package]
name = "unlock-center"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "unlock-center"
path = "src/main.rs"

[dependencies]
domain-index = { path = "../domain-index" }
schedule = { path = "../schedule" }
anyhow = { workspace = true }
arc-swap = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
dashmap = { workspace = true }
futures-util = { workspace = true }
hickory-proto = { workspace = true }
ipnet = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
rcgen = { workspace = true }
reqwest = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha1 = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
tokio-rustls = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
thiserror = { workspace = true }
zeroize = { workspace = true }
maxminddb = { workspace = true }
flate2 = { workspace = true }
